### ISSUE TITLE
menu broken

### ISSUE THREAD

**Issue by TianxSky** [JoaoRodrigoGoncalves/ServerCommands#9]
when pressing 7 and instead of going back the main menu it exits

**Comment by RitinhaUwU** [comment]
I'll see if I can take a look into it but be advised that I haven't touched CS:GO plugins in a while.

**Comment by RitinhaUwU** [comment]
On a fresh installation of metamod + sourcemod it works just fine.
Sourcemod 1.10.0-git6503 (windows)
Metamod 1.11.0-git1144 (windows)

![Untitled](https://user-images.githubusercontent.com/39278414/120514357-1b5d3900-c3c5-11eb-814c-efc8fbe699c7.gif)

Have you tried to update metamod/sourcemod and/or tried to check if the described issue occurs on other mod's menus?

**Comment by RitinhaUwU** [comment]
Issue abandoned. Can be opened again if needed.
